- platform: template
  switches:
    light_living_room:
      value_template: "{{ is_state('light.recessed_lights_level_9_0', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: light.recessed_lights_level_9_0
      turn_off:
        service: light.turn_off
        entity_id: light.recessed_lights_level_9_0
    light_dining_room:
      value_template: "{{ is_state('light.dining_room_light_level_8_0', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: light.dining_room_light_level_8_0
      turn_off:
        service: light.turn_off
        entity_id: light.dining_room_light_level_8_0
    light_kitchen:
      value_template: "{{ is_state('light.kitchen_light_level_5_0', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: light.kitchen_light_level_5_0
      turn_off:
        service: light.turn_off
        entity_id: light.kitchen_light_level_5_0
    light_entry:
      value_template: "{{ is_state('light.entry_light_level_7_0', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: light.entry_light_level_7_0
      turn_off:
        service: light.turn_off
        entity_id: light.entry_light_level_7_0
    light_outside:
      value_template: "{{ is_state('switch.outside_lights_switch_6_0', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.outside_lights_switch_6_0
      turn_off:
        service: switch.turn_off
        entity_id: switch.outside_lights_switch_6_0
    light_upstairs:
      value_template: "{{ is_state('group.upstairs_lights', 'on') }}"
      turn_on:
        service: homeassistant.turn_on
        entity_id: group.upstairs_lights
      turn_off:
        service: homeassistant.turn_off
        entity_id: group.upstairs_lights
    light_downstairs:
      value_template: "{{ is_state('group.downstairs_lights', 'on') }}"
      turn_on:
        service: homeassistant.turn_on
        entity_id: group.downstairs_lights
      turn_off:
        service: homeassistant.turn_off
        entity_id: group.downstairs_lights
    light_family_room:
      value_template: "{{ is_state('light.family_room_recessed_lights_level_16_0', 'on') }}"
      turn_on:
        service: light.turn_on
        entity_id: light.family_room_recessed_lights_level_16_0
      turn_off:
        service: light.turn_off
        entity_id: light.family_room_recessed_lights_level_16_0
    light_downstairs_hallway:
      value_template: "{{ is_state('switch.downstairs_hallway_switch_17_0', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.downstairs_hallway_switch_17_0
      turn_off:
        service: switch.turn_off
        entity_id: switch.downstairs_hallway_switch_17_0
    light_upstairs_hallway:
      value_template: "{{ is_state('switch.upstairs_hall_switch_14_0', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.upstairs_hall_switch_14_0
      turn_off:
        service: switch.turn_off
        entity_id: switch.upstairs_hall_switch_14_0
    light_downstairs_stairway:
      value_template: "{{ is_state('switch.downstairs_stairway_switch_15_0', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.downstairs_stairway_switch_15_0
      turn_off:
        service: switch.turn_off
        entity_id: switch.downstairs_stairway_switch_15_0
    light_all:
      value_template: "{{ is_state('group.inside_lights', 'on') }}"
      turn_on:
        service: homeassistant.turn_on
        entity_id: group.inside_lights
      turn_off:
        service: homeassistant.turn_off
        entity_id: group.inside_lights
